// Fallback data for reviews when database is not available
export const fallbackReviews = [
  {
    id: "fallback-1",
    order_id: null,
    user_id: null,
    customer_name: "Alex M.",
    customer_email: "alex@example.com",
    rating: 5,
    title: "Outstanding service! Got my account maxed super fast",
    content: "The team was incredibly professional and efficient. They completed my level boost in just 6 hours when they estimated 8-12. Communication was excellent throughout the process and they even threw in some extra stratagem unlocks. Definitely recommend!",
    purchased_item: "Elite Helldiver Bundle",
    purchase_value: 89.99,
    order_type: "bundle",
    completion_time_hours: 6.0,
    verified_purchase: true,
    helpful_count: 24,
    reported_count: 0,
    is_featured: true,
    is_approved: true,
    admin_notes: null,
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "fallback-2",
    order_id: null,
    user_id: null,
    customer_name: "Sarah K.",
    customer_email: "sarah@example.com",
    rating: 5,
    title: "Best boosting service I've used",
    content: "I've tried other services before but this one is by far the best. The boosters are clearly skilled players and they maintained my K/D ratio while completing the missions. Worth every penny!",
    purchased_item: "Liberation Campaign Completion",
    purchase_value: 45.00,
    order_type: "service",
    completion_time_hours: 4.0,
    verified_purchase: true,
    helpful_count: 18,
    reported_count: 0,
    is_featured: false,
    is_approved: true,
    admin_notes: null,
    created_at: "2025-01-14T14:30:00Z",
    updated_at: "2025-01-14T14:30:00Z",
  },
  {
    id: "fallback-3",
    order_id: null,
    user_id: null,
    customer_name: "Mike R.",
    customer_email: "mike@example.com",
    rating: 4,
    title: "Great results, minor delay but excellent quality",
    content: "The service took a bit longer than expected due to server issues, but the team kept me updated throughout. The final result was exactly what I wanted - all my mission objectives completed with bonus samples collected.",
    purchased_item: "Custom Mission Package",
    purchase_value: 65.50,
    order_type: "custom",
    completion_time_hours: 10.0,
    verified_purchase: true,
    helpful_count: 12,
    reported_count: 0,
    is_featured: false,
    is_approved: true,
    admin_notes: null,
    created_at: "2025-01-13T09:15:00Z",
    updated_at: "2025-01-13T09:15:00Z",
  },
  {
    id: "fallback-4",
    order_id: null,
    user_id: null,
    customer_name: "Emily T.",
    customer_email: "emily@example.com",
    rating: 5,
    title: "Incredible attention to detail",
    content: "Not only did they complete all my objectives, but they also optimized my loadout and gave me strategic tips for future missions. The personal touch really sets them apart from other services.",
    purchased_item: "Super Earth Elite Package",
    purchase_value: 129.99,
    order_type: "bundle",
    completion_time_hours: 8.0,
    verified_purchase: true,
    helpful_count: 31,
    reported_count: 0,
    is_featured: true,
    is_approved: true,
    admin_notes: null,
    created_at: "2025-01-12T16:45:00Z",
    updated_at: "2025-01-12T16:45:00Z",
  },
];

export const fallbackStats = {
  totalReviews: fallbackReviews.length,
  averageRating: fallbackReviews.reduce((sum, review) => sum + review.rating, 0) / fallbackReviews.length,
  ratingBreakdown: fallbackReviews.reduce((acc, review) => {
    acc[review.rating] = (acc[review.rating] || 0) + 1;
    return acc;
  }, {} as Record<number, number>),
  featuredReviews: fallbackReviews.filter(review => review.is_featured),
};
